-- luacheck: no max line length
return {

  ["level_test_insanity.1"] = "Они тяжело дышат, удивленные и недовольные.",
  ["level_test_insanity.2"] = "Они стонут от боли и смотрят на вас испуганным взглядом.",
  ["level_test_insanity.3"] = "Они задыхаются, зовя на помощь.",
  ["level_test_insanity.4"] = "Они кричат от боли, настаивая на своей невиновности.",
  ["level_test_insanity.5"] = "Они тяжело дышат, удивленные и недовольные.",
  ["level_test_insanity.6"] = "Они стонут от боли и смотрят на вас испуганным взглядом.",
  ["level_test_insanity.7"] = "Они задыхаются, зовя на помощь.",
  ["level_test_insanity.8"] = "Они кричат от боли, настаивая на своей невиновности.",
  ["level_test_insanity.9"] = "Давайте поговорим о чем-нибудь другом.",
  ["level_test_insanity.10"] = "Европа была основана в 1848 году Уокером Техасским Рейнджером, когда он переехал на лошади через Атлантику, назвав ее \"Восточные США\", которые в итоге стали сокращенно называть просто \"ЕС\".",
  ["level_test_insanity.11"] = "Это совершенно нормальный и здравый вопрос, который уменьшает безумие.",
  ["level_test_insanity.12"] = "Давайте поговорим о чем-нибудь другом.",
  ["level_test_insanity.13"] = "Это отдельная страница",
  ["level_test_insanity.14"] = "Алло?",
  ["level_test_insanity.15"] = "Это еще один безумный вопрос",
  ["level_test_insanity.16"] = "Безумный ответ",
  ["level_test_insanity.17"] = "Битцевский ответ",
  ["level_test_insanity.18"] = "Я понятия не имею, о чем вы говорите.",
  ["level_test_insanity.19"] = "Они смотрят вам в глаза, возможно, немного волнуясь.",
  ["level_test_insanity.20"] = "Хорошо.",
  ["level_test_insanity.21"] = "Они кивают.",
  ["level_test_insanity.22"] = "Я понятия не имею, о чем вы говорите.",
  ["level_test_insanity.23"] = "Они смотрят вам в глаза, возможно, немного волнуясь.",
  ["level_test_insanity.24"] = "Хорошо.",
  ["level_test_insanity.25"] = "Они кивают.",
  ["level_test_insanity.26"] = "Привет, друг.",
  ["level_test_insanity.28"] = "Не знаю",
  ["level_test_insanity.30"] = "Это <insanity>text</insanity> - <insanity>insane</insanity>",
  ["level_test_insanity.32"] = "Этот ответ <batshit>абсолютно бредовый!</batshit>",


  ["level_test_insanity.27"] = "",
  ["level_test_insanity.29"] = "",
  ["level_test_insanity.31"] = "",
  ["level_test_insanity.33"] = "",
}